server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /wsh #设置统一前缀
  #ignored-services: microservicecloud-provider-dept
  ignored-services: "*"  #忽略所有服务
  routes:
    mydept.serviceId: microservicecloud-provider-dept
    mydept.path: /mydept/**

info:
  app.name: wsh-microcloud
  company.name: www.2424234.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

