server:
  port: 80

spring:
  application:
    name: microservicecloud-consumer-dept

eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-consumer-80 #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud-consumer-80
  company.name: www.666.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

